---
- hosts: [A]
  tasks:
  - name: "Update pakages & Install curl"
    apt:
          update_cache: yes
          name: curl
          state: latest
  - name: "enable ufw and allow 1834 port"
    ufw:
            state: enabled
            rule: allow
            port: '1834'
            proto: tcp
  - name: "ufw allow 8080 port"
    ufw:
            rule: allow
            port: '8080'
            proto: tcp
  - name: "ufw allow 80 port"
    ufw:
            rule: allow
            port: '80'
            proto: tcp
  - name: "ssh port 1834"
    lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#Port 22'
            line: 'Port 1834'
  - name: "Publickey"
    lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#PubkeyAuthentication yes'
            line: 'PubkeyAuthentication yes'
  - name: "Create user Webdeveloper"
    user:
            name: Webdeveloper
            password: S52we9V6QTp7
  - name: "Create user Devopsengineer"
    user:
            name: Devopsengineer
            password: dHy6sKGHsj2T
  - name: "Create user Projectmanager"
    user:
            name: Projectmanager
            password: oP92ugMSaCbe
  - name: "authorized key ssh"
    authorized_key:
            user: Webdeveloper
            state: present
            key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM= 
  - name: "authorized key ssh"
    authorized_key:
            user: Devopsengineer
            state: present
            key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM= 
  - name: "authorized key ssh"
    authorized_key:
            user: Projectmanager
            state: present
            key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM= 
  - name: "install docker"
    apt:
            name: docker
            state: latest
  - name: "transfer script"
    copy:
            src: ~/wsr-skillcloud/docker-compose.sh
            dest: /etc/docker-compose.sh
            owner: root
            mode: u+rwx,g-rwx,o-rwx
  - name: "Start script"
    shell: /etc/docker-compose.sh
  - name: "Create directory"
    file:
            path: ~/skillcloud-nginx
            state: directory
  - name: "transfer docker-compose.yml"
    copy:
            src: ~/wsr-skillcloud/docker-compose.yml
            dest: ~/skillcloud-nginx
  - name: "transfer Dockerfile-balance"
    copy:
            src: ~/wsr-skillcloud/Dockerfile-balance
            dest: ~/skillcloud-nginx
  - name: "Dockerfile-site"
    copy:
            src: ~/wsr-skillcloud/Dockerfile-site
            dest: ~/skillcloud-nginx
  - name: "transfer index.html"
    copy:
            src: ~/wsr-skillcloud/index.html
            dest: ~/skillcloud-nginx
  - name: "transfer nginx.conf"
    copy:
            src: ~/wsr-skillcloud/nginx.conf
            dest: ~/skillcloud-nginx
    
  - name: "Restart ufw"
    systemd:
            name: ufw
            state: restarted
            daemon_reload: yes
  - name: "restart ssh"
    systemd:
            name: ssh
            state: restarted
            daemon_reload: yes
  - name: "nginx.conf write ip address project1"
    replace:
            path: ~/skillcloud-nginx/nginx.conf
            regexp: '^server {\{\ IP_address_project_1 }\}\:8080;'
            replace: 'server 192.168.180.101:8080;'
